name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pensjon
    steps:
      - uses: actions/checkout@v4

      - uses: gradle/wrapper-validation-action@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Setup Gradle (cache)
        uses: gradle/actions/setup-gradle@v3
        with:
          build-root-directory: ./pension-api

      - name: Build (compile + tests)
        run: ./gradlew build --no-daemon
